-- Warning, RojoFriendlyEvents relies on lib "EventRateLimiter".
-- It will not work properly without it. 


---------------------------------------------------------------
--[[
    This library is meant to replace standard hardcoded Remote/Bindable system with a more dynamic and promise based one.
    It is highly recommended that you still create manually any and all events, though using RojoFriendlyEvents should prevent 
    most of compatibility issues and ensure a generally smooth experience. 
]]